gz_ros2_control:
  ros__parameters:
    hold_joints: false
    position_proportional_gain: 0.5

controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    pos_cont:
      type: position_controllers/JointGroupPositionController
    
    vel_cont:
      type: velocity_controllers/JointGroupVelocityController
      
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

pos_cont:
  ros__parameters:
    joints:
      - base_link_to_link1
      - link1_to_link2
      - link2_to_link3
      - link3_to_gripper_link

    gains:
      base_link_to_link1:
        position: 0.5


vel_cont:
  ros__parameters:
    joints:
      - base_link_to_link1
      - link1_to_link2
      - link2_to_link3
      - link3_to_gripper_link
