controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - base_link_to_link1
      - link1_to_link2
      - link2_to_link3
      - link3_to_gripper_link

    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity
